stages:
  DATA_INGESTION:
    cmd: python src/stage_01_data_ingestion.py
    deps:
      - src/stage_01_data_ingestion.py
      - src/utils/common.py
      - src/data_processing/data_validation.py
      - src/data_processing/data_transformation.py
      - src/data_processing/load_data.py
      - src/db_operation/db_operations.py
      - configs/config.py
    outs:
      - artifacts/sql_data_dir/Insurance_fraud_validated_data_db.db

  DATA_PROCESSING:
    cmd: python src/stage_02_data_processing.py
    deps:
      - src/stage_02_data_processing.py
      - src/utils/common.py
      - configs/config.py
      - src/data_processing/data_preprocessing.py
      - src/db_operation/db_operations.py
      - artifacts/sql_data_dir/Insurance_fraud_validated_data_db.db
    outs:
      - artifacts/local_data_dir/valid_data/model_training_validated_data_file.csv
      - artifacts/local_data_dir/processed_data/

# Other stages...

